# Use root/example as user/password credentials
# version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-project-example # too lazy to change lol
      MONGO_INITDB_ROOT_PASSWORD: root-project-example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root-project-example
      ME_CONFIG_MONGODB_ADMINPASSWORD: root-project-example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
