import {EventObject} from "@/lib/models/events";

export const testEvents: EventObject[] = [
  {
    id: "evt-001",
    title: "Annual Tech Conference 2025",
    body: "Join us for the biggest tech conference of the year featuring keynote speakers, workshops, and networking opportunities.",
    description: "A three-day immersive experience showcasing the latest in AI, blockchain, and cloud computing.",
    organizer: "TechCorp Industries",
    date: new Date("2025-06-15T09:00:00"),
    location: "San Francisco Convention Center",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 245,
    maxAttendees: 500,
    contact: "events@techcorp.com",
    price: 299.99,
    isPublic: true,
    tags: ["Career", "Workshop", "Academic"]
  },
  {
    id: "evt-002",
    title: "Community Garden Volunteer Day",
    body: "Help us plant new vegetables and maintain our community garden space.",
    description: "A family-friendly event where participants will learn about sustainable gardening practices while beautifying our neighborhood.",
    organizer: "Green Thumb Community Group",
    date: new Date("2025-05-10T10:00:00"),
    location: "Oakridge Community Garden",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 18,
    maxAttendees: 30,
    contact: "coordinator@greenthumb.org",
    isPublic: true,
    tags: ["Social"]
  },
  {
    id: "evt-003",
    title: "Executive Board Strategic Planning",
    body: "Quarterly closed meeting for executive team members to discuss Q3 strategic initiatives.",
    description: "Confidential planning session to align on priorities and resource allocation for upcoming quarter.",
    organizer: "Office of the CEO",
    date: new Date("2025-05-02T13:00:00"),
    location: "Executive Boardroom - 15th Floor",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 7,
    maxAttendees: 10,
    isPublic: false,
    tags: ["Career"]
  },
  {
    id: "evt-004",
    title: "Summer Music Festival",
    body: "Three stages featuring local and national artists across multiple genres.",
    description: "Our annual outdoor music celebration with food vendors, art installations, and family activities.",
    organizer: "SoundWaves Productions",
    date: new Date("2025-07-18T12:00:00"),
    location: "Riverfront Park",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 1240,
    maxAttendees: 2000,
    contact: "tickets@soundwaves.com",
    price: 45.50,
    isPublic: true,
    tags: ["Arts", "Social"]
  },
  {
    id: "evt-005",
    title: "Virtual Book Club: May Selection",
    body: "Discussion of 'The Quantum Horizon' by Dr. Eliza Chen.",
    description: "Monthly online gathering to analyze themes, characters, and writing style of our latest book selection.",
    organizer: "Digital Bookworms",
    date: new Date("2025-05-20T19:00:00"),
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 23,
    contact: "bookclub@digitalbookworms.net",
    isPublic: true,
    tags: ["Academic", "Social"]
  },
  {
    id: "evt-006",
    title: "Product Launch: NextGen Smart Home Suite",
    body: "Exclusive preview of our revolutionary smart home ecosystem for industry partners and press.",
    description: "Be the first to experience our integrated solution that combines security, energy management, and lifestyle automation.",
    organizer: "HomeTech Innovations",
    date: new Date("2025-05-30T18:00:00"),
    location: "The Grand Hotel Ballroom",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 87,
    maxAttendees: 150,
    contact: "launch@hometech.com",
    isPublic: false,
    tags: ["Career", "Workshop"]
  },
  {
    id: "evt-007",
    title: "Startup Pitch Night",
    body: "Watch emerging startups pitch their groundbreaking ideas to investors and the community.",
    description: "A lively evening where selected startups will showcase innovations in tech, health, and sustainability to a panel of investors.",
    organizer: "VentureConnect",
    date: new Date("2025-06-05T17:30:00"),
    location: "Innovation Hub Auditorium",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 320,
    maxAttendees: 400,
    contact: "info@ventureconnect.com",
    price: 15.00,
    isPublic: true,
    tags: ["Career", "Social", "Workshop"]
  },
  {
    id: "evt-008",
    title: "Coding Bootcamp: Web Development 101",
    body: "Learn the basics of modern web development in this hands-on crash course.",
    description: "A full-day intensive bootcamp covering HTML, CSS, JavaScript, and frontend best practices.",
    organizer: "SkillForge Academy",
    date: new Date("2025-05-25T09:00:00"),
    location: "SkillForge Downtown Campus",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 50,
    maxAttendees: 75,
    contact: "contact@skillforge.com",
    price: 99.00,
    isPublic: true,
    tags: ["Academic", "Workshop"]
  },
  {
    id: "evt-009",
    title: "Mindfulness Meditation Workshop",
    body: "Cultivate calm and focus through mindfulness techniques taught by certified instructors.",
    description: "A gentle introduction to mindfulness meditation practices, breathwork, and body awareness.",
    organizer: "Inner Peace Collective",
    date: new Date("2025-06-10T10:00:00"),
    location: "Willow Yoga Studio",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 25,
    maxAttendees: 40,
    contact: "info@innerpeace.org",
    price: 20.00,
    isPublic: true,
    tags: ["Social", "Workshop"]
  },
  {
    id: "evt-010",
    title: "Art Exhibition: The Future Reimagined",
    body: "Experience thought-provoking installations from emerging digital artists.",
    description: "An avant-garde showcase of multimedia artworks exploring the theme of technology and humanity.",
    organizer: "Modern Arts Society",
    date: new Date("2025-07-05T18:00:00"),
    location: "City Art Gallery",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 140,
    maxAttendees: 200,
    contact: "exhibitions@modernarts.org",
    price: 12.00,
    isPublic: true,
    tags: ["Arts"]
  },
  {
    id: "evt-011",
    title: "Annual Charity Gala",
    body: "An elegant evening of fine dining and philanthropy.",
    description: "Join local leaders and philanthropists to support youth education initiatives.",
    organizer: "Future Scholars Foundation",
    date: new Date("2025-08-22T19:00:00"),
    location: "Metropolitan Grand Ballroom",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 500,
    maxAttendees: 600,
    contact: "rsvp@futurescholars.org",
    price: 250.00,
    isPublic: true,
    tags: ["Social", "Career"]
  },
  {
    id: "evt-012",
    title: "Workshop: Fundamentals of Data Science",
    body: "Understand key concepts in data analysis, modeling, and visualization.",
    description: "A beginner-friendly workshop focusing on the practical side of data science with Python.",
    organizer: "DataNexus Institute",
    date: new Date("2025-06-28T14:00:00"),
    location: "TechCampus Room 203",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 80,
    maxAttendees: 100,
    contact: "info@datanexus.io",
    price: 120.00,
    isPublic: true,
    tags: ["Academic", "Workshop"]
  },
  {
    id: "evt-013",
    title: "Film Screening: 'Beyond the Horizon'",
    body: "Special premiere of the critically acclaimed sci-fi documentary.",
    description: "A visual journey exploring the possibility of life beyond our planet.",
    organizer: "Cosmos Society",
    date: new Date("2025-07-12T20:00:00"),
    location: "City Theater 5",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 210,
    maxAttendees: 300,
    contact: "screenings@cosmossociety.org",
    price: 18.00,
    isPublic: true,
    tags: ["Arts", "Social"]
  },
  {
    id: "evt-014",
    title: "Weekend Hackathon: AI for Good",
    body: "Solve real-world problems through AI applications in this 48-hour hackathon.",
    description: "Bring your laptop, form teams, and build tech solutions to societal challenges with guidance from mentors.",
    organizer: "Tech4Good Foundation",
    date: new Date("2025-08-02T09:00:00"),
    location: "Impact Hub Downtown",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 180,
    maxAttendees: 250,
    contact: "hackathons@tech4good.org",
    isPublic: true,
    tags: ["Career", "Workshop"]
  },
  {
    id: "evt-015",
    title: "Local Farmer's Market",
    body: "Fresh produce, handmade goods, and live music every Saturday morning.",
    description: "Support local farmers and artisans while enjoying community vibes.",
    organizer: "City Farmer's Association",
    date: new Date("2025-05-17T08:00:00"),
    location: "Main Street Plaza",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 350,
    isPublic: true,
    tags: ["Social"]
  },
  {
    id: "evt-016",
    title: "Photography Walk: Urban Landscapes",
    body: "Capture the essence of the city through your lens on a guided photo walk.",
    description: "Tips, tricks, and exploration led by a professional urban photographer.",
    organizer: "CityLens Collective",
    date: new Date("2025-06-03T16:00:00"),
    location: "Central Station",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 60,
    maxAttendees: 80,
    contact: "walks@citylens.org",
    price: 10.00,
    isPublic: true,
    tags: ["Arts", "Social"]
  },
  {
    id: "evt-017",
    title: "Virtual Career Fair: Summer Edition",
    body: "Meet top employers and explore job opportunities — all from your computer.",
    description: "Live sessions, resume reviews, and interview coaching with recruiters.",
    organizer: "CareerPathways",
    date: new Date("2025-06-22T11:00:00"),
    attendees: 600,
    contact: "info@careerpathways.com",
    isPublic: true,
    tags: ["Career", "Academic"]
  },
  {
    id: "evt-018",
    title: "Cooking Class: Mediterranean Flavors",
    body: "Learn to prepare delicious Mediterranean dishes with a professional chef.",
    description: "A hands-on cooking workshop featuring appetizers, mains, and desserts from Greece, Italy, and Spain.",
    organizer: "TasteMakers Studio",
    date: new Date("2025-05-27T17:00:00"),
    location: "TasteMakers Downtown Kitchen",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 20,
    maxAttendees: 25,
    contact: "classes@tastemakers.com",
    price: 60.00,
    isPublic: true,
    tags: ["Social", "Workshop"]
  },
  {
    id: "evt-019",
    title: "Public Lecture: The Future of Renewable Energy",
    body: "Renowned climate scientist Dr. Maria Evans shares insights into clean energy solutions.",
    description: "An eye-opening presentation and Q&A session on the next era of green technology.",
    organizer: "EcoWorld University",
    date: new Date("2025-06-17T18:30:00"),
    location: "EcoWorld Lecture Hall",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 100,
    maxAttendees: 150,
    contact: "lectures@ecoworld.edu",
    isPublic: true,
    tags: ["Academic", "Career"]
  },
  {
    id: "evt-020",
    title: "Annual Bike Race",
    body: "Compete or cheer at the city's biggest cycling event of the year.",
    description: "Participants will race through a 50-mile route across urban and scenic trails, with festivities after the finish line.",
    organizer: "CycleCity Club",
    date: new Date("2025-09-01T07:00:00"),
    location: "City Sports Arena",
    thumbnail: "https://random-image-pepebigotes.vercel.app/api/random-image",
    attendees: 800,
    maxAttendees: 1000,
    contact: "race@cyclecity.org",
    price: 50.00,
    isPublic: true,
    tags: ["Social"]
  }
];

export const testStudent = {
  name: "Alex Johnson",
  major: "Computer Science",
  year: "Junior",
  avatar: "/placeholder.svg?height=40&width=40",
  interests: ["Technology", "Sports", "Arts", "Research"],
  organizations: ["CS Club", "Husky Running Club", "Student Government"],
}